/// Flutter icons Fitness_App
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fitness_App
///      fonts:
///       - asset: fonts/Fitness_App.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Fitness_App {
  Fitness_App._();

  static const _kFontFam = 'Fitness_App';
  static const String _kFontPkg = null;

  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tray = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
